"""PR B -- Layer 1 tables (projects, reports, rag_queries) + RLS on 5 tables

Revision ID: 20dfc6b1520e
Revises: f619dbdc7ef5
Create Date: 2026-08-09 17:42:05.171728

RLS section (hand-written, not autogenerated -- SQLAlchemy's model layer has
no RLS abstraction) requires the nce_app_scoped role. This migration DOES
create the role itself (idempotently, via a DO block, since Postgres has no
CREATE ROLE IF NOT EXISTS) -- role EXISTENCE is reproducible schema state
like anything else here, not a secret, and belongs in git so `alembic
upgrade head` alone is sufficient to reach a working state on any
environment, not dependent on someone remembering an undocumented manual
step (a real gap in an earlier draft of this migration, caught in review).

Only the role's PASSWORD is out of band -- that genuinely is a secret, and
one baked into a git-committed file is exactly the kind of leak this
codebase avoids elsewhere (see backend/tenant_db/base.py's and
alembic/env.py's own DATABASE_URL handling). The role is created here with
NO password (cannot log in until one is set); set the real one once, out of
band, after running this migration:

    ALTER ROLE nce_app_scoped WITH PASSWORD '<generated>';

Then build TENANT_SCOPED_DATABASE_URL from it and set that on the web
service (render.yaml documents this) -- the app does not connect as
nce_app_scoped, and RLS is not actually enforced against it in production,
until that env var is set. It is not set as of this migration landing.

Everything else (schema usage, table grants, RLS enable, policies) is
ordinary deterministic DDL with no secret material, and lives in this
migration like any other schema change.

Policy shape, identical across all 5 tables: a row is visible/writable only
when its tenant_id matches the CURRENT transaction's
`app.current_tenant_id` setting (see backend/tenant_db/scoped.py for how
that gets set safely — SET LOCAL, per-transaction, never plain SET). RLS is
enabled but NOT forced for the table owner (nce_tenant_db_user) — Postgres
never restricts an owning role unless FORCE ROW LEVEL SECURITY is also set,
and it deliberately is not here: PR A's admin endpoints (list_tenants,
approve_tenant, etc.) connect as that owner and need real cross-tenant
visibility. Only nce_app_scoped (a non-owner role, so RLS applies to it
automatically) is actually restricted by these policies.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20dfc6b1520e'
down_revision: Union[str, Sequence[str], None] = 'f619dbdc7ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RLS_TABLES = ["tenants", "users", "projects", "reports", "rag_queries"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('rag_queries',
    sa.Column('query_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('sources_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('raqs_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###

    # ── RLS (hand-written) ──────────────────────────────────────────────
    # Idempotent role-shell creation — NO password (see module docstring).
    # Postgres has no CREATE ROLE IF NOT EXISTS, hence the DO block.
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'nce_app_scoped') THEN
                CREATE ROLE nce_app_scoped LOGIN
                    NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
            END IF;
        END
        $$
    """)
    op.execute("GRANT USAGE ON SCHEMA public TO nce_app_scoped")
    for table in _RLS_TABLES:
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO nce_app_scoped")
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY tenant_isolation ON {table}
                USING (tenant_id::text = current_setting('app.current_tenant_id', true))
                WITH CHECK (tenant_id::text = current_setting('app.current_tenant_id', true))
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ── RLS (hand-written) ──────────────────────────────────────────────
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
        op.execute(f"REVOKE SELECT, INSERT, UPDATE, DELETE ON {table} FROM nce_app_scoped")
    op.execute("REVOKE USAGE ON SCHEMA public FROM nce_app_scoped")
    op.execute("DROP ROLE IF EXISTS nce_app_scoped")
    # NOTE: re-running upgrade() after this recreates the role with NO
    # password (same as a first-time upgrade) — the ALTER ROLE ... WITH
    # PASSWORD step in this file's docstring needs re-running too.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('rag_queries')
    op.drop_table('projects')
    # ### end Alembic commands ###
