"""PR C -- user_events table + RLS

Revision ID: c561c9c9acc7
Revises: 20dfc6b1520e
Create Date: 2026-08-09 19:00:37.628180

nce_app_scoped already exists (created idempotently by PR B's migration,
20dfc6b1520e) -- this migration does NOT recreate it, only extends its
grants to the new table. Same policy shape as PR B's 5 tables: a row is
visible/writable only when its tenant_id matches the current transaction's
app.current_tenant_id setting (see backend/tenant_db/scoped.py). RLS
enabled but not forced for the owner (nce_tenant_db_user), same reasoning
as PR B -- admin/system code using the owner connection is unaffected.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c561c9c9acc7'
down_revision: Union[str, Sequence[str], None] = '20dfc6b1520e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###

    # ── RLS (hand-written, same pattern as PR B) ────────────────────────
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON user_events TO nce_app_scoped")
    op.execute("ALTER TABLE user_events ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON user_events
            USING (tenant_id::text = current_setting('app.current_tenant_id', true))
            WITH CHECK (tenant_id::text = current_setting('app.current_tenant_id', true))
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ── RLS (hand-written) ──────────────────────────────────────────────
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON user_events")
    op.execute("ALTER TABLE user_events DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON user_events FROM nce_app_scoped")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_events')
    # ### end Alembic commands ###
